#!/usr/bin/bash

if [[ $1 == "install" ]]; then
    command sudo apt install ${@:2}
fi
if [[ $1 == "remove" ]]; then
    appname="${@:2}"

    if [ -z "$2" ]; then
      appname=$(sudo apt list --installed | fzf | awk -F'/' '{print $1}')
    fi

    command sudo apt remove $appname
    command sudo apt autoremove
fi
if [[ $1 == "uninstall" ]]; then
    command sudo apt remove ${@:2}
    command sudo apt autoremove
fi
if [[ $1 == "update" ]]; then
    command sudo apt update
fi
if [[ $1 == "aurupdate" ]]; then
    command yay -Quq --aur | xargs -n 1 yay -S --noconfirm
fi
if [[ $1 == "list" ]]; then
    command apt list --installed
fi
